[package]
name = "Poker-Validator"
version = "0.1.0"
edition = "2021"


[dependencies]
strum = "0.24.1"
strum_macros = "0.24.3"
itertools = "0.10.5"
dialoguer = "0.10.3"
console = "0.9.1"
#colored = "2.0.0"